# Generated by Django 5.0.4 on 2024-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20)),
                ('bank_address', models.CharField(max_length=20)),
                ('services', models.CharField(max_length=20)),
                ('total_customers', models.IntegerField()),
                ('branch_manager', models.CharField(max_length=20)),
            ],
        ),
    ]
